version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Australia/Sydney
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - dependencies
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
      - dependency-name: typescript
        update-types:
          - "version-update:semver-major"
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Australia/Sydney
    labels:
      - dependencies
    groups:
      actions:
        patterns:
          - "*"
