import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, Code2, GitPullRequest, Scale, Users } from "lucide-react";
import { InfoPage } from "@/components/info-page";

export const metadata: Metadata = { title: "Open source project", description: "How OpenBIMI is built, governed, licensed, and developed in public." };

export default function OpenPage() {
  return <InfoPage eyebrow="Open project" title={<>Built in public.<br /><em>Useful to everyone.</em></>} intro="OpenBIMI’s checker, validators, UI, and guidance are available for inspection and reuse. Product decisions and corrections belong in the public repository." updated="2 August 2026">
    <section><h2>What “open” means here</h2><div className="info-card-grid"><div className="info-card"><Code2 aria-hidden="true" /><h3>Source available</h3><p>Inspect the exact code that performs DNS checks, parses records, validates SVG files, and renders results.</p></div><div className="info-card"><Scale aria-hidden="true" /><h3>Apache 2.0 today</h3><p>The repository currently uses the Apache License 2.0. Any future licensing change will be discussed publicly before it lands.</p></div><div className="info-card"><GitPullRequest aria-hidden="true" /><h3>Corrections welcome</h3><p>Technical issues, source updates, accessibility fixes, and clear documentation improvements can be proposed on GitHub.</p></div><div className="info-card"><Users aria-hidden="true" /><h3>No pay-to-rank</h3><p>Provider and certificate guidance is neutral. OpenBIMI does not accept commissions for rankings or referrals.</p></div></div></section>
    <section><h2>Current delivery phases</h2><ol className="roadmap-list"><li className="is-done"><span>1</span><div><strong>Foundation</strong><p>Public repository, brand system, CI, tests, Vercel deployment, and domain.</p></div></li><li className="is-current"><span>2</span><div><strong>Anonymous alpha</strong><p>Checker, setup wizard, logo converter, record builder, header inspector, provider matrix, and learning content.</p></div></li><li><span>3</span><div><strong>Managed beta</strong><p>DNS claims, recovery keys, managed asset hosting, certificate validation, daily checks, and alerts.</p></div></li><li><span>4</span><div><strong>Public v1</strong><p>Capacity expansion, public API documentation, operational runbooks, self-hosting, and measured cost reporting.</p></div></li></ol></section>
    <section className="info-callout"><div><h2>Read or improve the source</h2><p>The GitHub repository is the project’s working record.</p></div><a className="button button--dark" href="https://github.com/suped-com/openbimi" target="_blank" rel="noreferrer">Open GitHub <ArrowUpRight size={16} aria-hidden="true" /></a></section>
    <section><h2>Project documents</h2><div className="info-link-list"><a href="https://github.com/suped-com/openbimi/blob/main/LICENSE">License <ArrowUpRight size={14} aria-hidden="true" /></a><a href="https://github.com/suped-com/openbimi/issues">Issues <ArrowUpRight size={14} aria-hidden="true" /></a><a href="https://github.com/suped-com/openbimi/discussions">Discussions <ArrowUpRight size={14} aria-hidden="true" /></a><Link href="/security">Security disclosure</Link></div></section>
  </InfoPage>;
}
