import type { Metadata } from "next";
import { ArrowUpRight, EyeOff, FileWarning, Network, ShieldCheck } from "lucide-react";
import { InfoPage } from "@/components/info-page";

export const metadata: Metadata = { title: "Security and vulnerability disclosure", description: "OpenBIMI’s security boundaries and private vulnerability-reporting process." };

export default function SecurityPage() {
  return <InfoPage eyebrow="Security" title={<>Report quietly.<br /><em>Fix openly.</em></>} intro="Protecting visitors and third-party domains matters more than public proof. Please report suspected vulnerabilities privately before disclosure." updated="2 August 2026">
    <section className="info-callout"><div><h2>Report a vulnerability privately</h2><p>Include the affected path, impact, safe reproduction steps, and any suggested mitigation. Do not include unnecessary personal data.</p></div><a className="button button--dark" href="https://github.com/suped-com/openbimi/security/advisories/new" target="_blank" rel="noreferrer">Open private report <ArrowUpRight size={16} aria-hidden="true" /></a></section>
    <section><h2>Current security boundaries</h2><div className="info-card-grid"><div className="info-card"><Network aria-hidden="true" /><h3>Remote fetch controls</h3><p>Checker requests require public HTTPS targets, reject local and private addresses, revalidate redirects, and enforce time and size limits.</p></div><div className="info-card"><FileWarning aria-hidden="true" /><h3>Restricted SVG</h3><p>The validator rejects scripts, animation, external references, entities, embedded raster images, and interactive elements.</p></div><div className="info-card"><EyeOff aria-hidden="true" /><h3>Local sensitive tools</h3><p>Original logo artwork and pasted email headers remain in the browser and are not sent to OpenBIMI.</p></div><div className="info-card"><ShieldCheck aria-hidden="true" /><h3>Minimal state</h3><p>The anonymous alpha has no user accounts, domain claims, persistent reports, or stored customer assets.</p></div></div></section>
    <section><h2>Safe-harbour expectations</h2><ul><li>Use only accounts, files, and domains you own or have explicit permission to test.</li><li>Do not access, retain, alter, or disclose another person’s data.</li><li>Do not degrade service, run denial-of-service tests, spam endpoints, or test third-party infrastructure through OpenBIMI.</li><li>Stop when you confirm a vulnerability; do not pivot or establish persistence.</li><li>Allow reasonable time for investigation and remediation before coordinated disclosure.</li></ul></section>
    <section><h2>Useful report details</h2><p>A concise report should identify the affected component and version, the preconditions, exact low-impact reproduction steps, observed versus expected behaviour, security impact, and any logs or screenshots that do not expose unrelated data.</p></section>
    <section><h2>Not security vulnerabilities</h2><p>Provider refusal to display a logo, DNS propagation delays, mail reputation outcomes, missing certificates, and ordinary validation disagreements are usually product or standards issues. Report those in the public issue tracker after removing sensitive material.</p><div className="info-link-list"><a href="https://github.com/suped-com/openbimi/issues/new" target="_blank" rel="noreferrer">Open a product issue</a></div></section>
  </InfoPage>;
}
