import type { Metadata } from "next";
import { InfoPage } from "@/components/info-page";

export const metadata: Metadata = { title: "Terms and conditions", description: "Fair-use, accuracy, responsibility, and open-source terms for OpenBIMI." };

export default function TermsPage() {
  return <InfoPage eyebrow="Terms and conditions" title={<>Open tools.<br /><em>Clear boundaries.</em></>} intro="These terms apply to the hosted OpenBIMI website and anonymous tools. By using the service, you agree to use it lawfully and understand what its results can—and cannot—prove." updated="2 August 2026">
    <section><h2>1. The service</h2><p>OpenBIMI provides informational tools for Brand Indicators for Message Identification, public DNS and HTTPS diagnostics, local file conversion and validation, record generation, and educational content. The hosted service is currently an alpha and may change, be limited, or be unavailable without notice.</p></section>
    <section><h2>2. No display guarantee</h2><p>A passing result does not guarantee that a mailbox provider will display a logo. Providers apply their own authentication, evidence, reputation, volume, abuse, caching, and interface policies. OpenBIMI does not issue VMCs or CMCs and cannot determine whether an issuer will approve an application.</p></section>
    <section><h2>3. Your responsibility</h2><ul><li>Confirm that you control or are authorised to use the domains, logos, certificates, and other material you enter.</li><li>Review all generated DNS values and files before publishing them.</li><li>Inventory and authenticate legitimate senders before strengthening DMARC enforcement.</li><li>Obtain professional security, legal, trademark, or deliverability advice where appropriate.</li><li>Keep recovery material secure if managed-domain features become available later.</li></ul></section>
    <section><h2>4. Fair use</h2><p>Do not abuse the service, interfere with its operation, bypass limits, probe private networks, scan domains at harmful volume, upload malicious content, impersonate others, or use results to misrepresent brand ownership. Bulk operators should run or adapt the open-source project rather than impose disproportionate cost on the public hosted service.</p></section>
    <section><h2>5. Intellectual property</h2><p>You retain rights in material you process. You grant only the temporary technical permission necessary for a requested public check; local logo and header tools do not upload their inputs. The OpenBIMI source code is available under the license in the repository. Third-party names, marks, standards, and linked documentation belong to their respective owners.</p></section>
    <section><h2>6. Availability and warranties</h2><p>The service is provided on an “as is” and “as available” basis to the extent permitted by law. We do not promise uninterrupted availability, complete or error-free results, fitness for a particular purpose, or that guidance remains current after a provider or specification change. Nothing in these terms excludes rights or remedies that cannot lawfully be excluded.</p></section>
    <section><h2>7. Limitation and changes</h2><p>To the extent permitted by law, project contributors are not responsible for indirect, consequential, or special loss arising from use of the service or reliance on a result. We may restrict abusive use and update these terms as the product changes. The “last updated” date records the current version.</p></section>
    <section><h2>8. Questions</h2><p>Use GitHub Discussions for general terms questions. Do not place confidential information in a public issue or discussion.</p><div className="info-link-list"><a href="https://github.com/suped-com/openbimi/discussions" target="_blank" rel="noreferrer">Open project discussions</a></div></section>
  </InfoPage>;
}
