import type { Metadata } from "next";
import { InfoPage } from "@/components/info-page";

export const metadata: Metadata = { title: "Privacy policy", description: "How OpenBIMI handles public checks, local files, technical logs, and personal information." };

export default function PrivacyPage() {
  return <InfoPage eyebrow="Privacy policy" title={<>Useful diagnostics.<br /><em>Minimum data.</em></>} intro="OpenBIMI is designed to work without an account. This policy explains what the current anonymous service processes and what it deliberately does not collect." updated="2 August 2026">
    <section><h2>1. Scope</h2><p>This policy applies to openbimi.com and its current anonymous checker, setup wizard, local logo tools, local email-header inspector, record builder, and learning pages. Managed hosting, accounts, notifications, and domain claims are not currently available; this policy will be updated before those features launch.</p></section>
    <section><h2>2. Information processed</h2><h3>Public-domain checks</h3><p>When you check a domain, the server receives the domain and optional BIMI selector. It queries public DNS records and may request the public HTTPS logo or certificate URL published in those records. The application returns the result to your browser and does not intentionally store a report history.</p><h3>Logo artwork</h3><p>Files selected in the logo converter, SVG validator, or setup wizard are processed locally in your browser. Original artwork is not uploaded to OpenBIMI.</p><h3>Email headers</h3><p>Headers pasted into the header inspector are parsed locally in your browser. They are not submitted to OpenBIMI. Headers can contain personal information such as email addresses, IP addresses, message IDs, and mail-routing details, so do not share them publicly without review.</p><h3>Technical request data</h3><p>Our hosting provider may process normal web-request information needed to deliver and secure the site, such as IP address, user agent, requested path, timestamps, and runtime logs. Its handling and retention are controlled by the hosting platform and our project configuration.</p></section>
    <section><h2>3. What the current site does not use</h2><ul><li>No general user accounts.</li><li>No advertising or cross-site tracking.</li><li>No marketing mailing list.</li><li>No DMARC aggregate-report ingestion.</li><li>No intentional storage of anonymous checker results, original artwork, or pasted headers.</li></ul><p>The site may use strictly necessary platform mechanisms required for security or delivery. If analytics or optional notifications are added later, this policy and the interface will be updated first.</p></section>
    <section><h2>4. Service providers and international processing</h2><p>OpenBIMI is hosted on Vercel. Requests can be processed through infrastructure in multiple countries. Public DNS resolvers and the third-party hosts that serve a domain’s published BIMI files also receive the technical requests necessary to answer a check.</p><div className="info-link-list"><a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noreferrer">Vercel privacy policy</a></div></section>
    <section><h2>5. Security and retention</h2><p>Remote requests are bounded by protocol, address, redirect, timeout, and size checks. Local-tool content remains in the current browser tab unless you download it. Normal platform logs may remain for the period provided by Vercel or required for security, troubleshooting, and legal obligations.</p></section>
    <section><h2>6. Access, correction, and questions</h2><p>Because the current service does not create user profiles or intentionally retain tool inputs, OpenBIMI will usually have no account record to access or correct. For a general privacy question, open a GitHub discussion without including private data. For a sensitive security or privacy issue, use the repository’s private security-reporting channel.</p><div className="info-link-list"><a href="https://github.com/suped-com/openbimi/discussions" target="_blank" rel="noreferrer">General questions</a><a href="https://github.com/suped-com/openbimi/security/advisories/new" target="_blank" rel="noreferrer">Private security report</a></div></section>
    <section><h2>7. Changes</h2><p>Material changes will be reflected by a new “last updated” date. Features that materially change data collection—such as managed hosting, recovery keys, or email alerts—will receive specific disclosures before activation.</p></section>
  </InfoPage>;
}
