import type { Metadata } from "next";
import { ArrowUpRight, Database, HardDrive, Server, WalletCards } from "lucide-react";
import { InfoPage } from "@/components/info-page";

export const metadata: Metadata = { title: "Operating costs", description: "OpenBIMI’s current infrastructure footprint, cost model, and planned public reporting." };

export default function CostsPage() {
  return <InfoPage eyebrow="Cost transparency" title={<>Free to use.<br /><em>Honest about cost.</em></>} intro="The anonymous alpha uses an existing Vercel Pro team. No database, managed object store, scheduled monitoring, or transactional email service is active for OpenBIMI yet." updated="2 August 2026">
    <section><h2>Current incremental footprint</h2><div className="cost-banner"><div><span>Expected additional monthly platform cost</span><strong>Approximately US$0</strong><p>while traffic remains inside unused existing Vercel Pro allowances</p></div><WalletCards aria-hidden="true" /></div><p>This is an engineering estimate, not a promise that infrastructure has no cost. The Suped team already pays for Vercel Pro, domain registration is separate, and usage growth can create overages. OpenBIMI does not yet publish invoice-derived monthly totals.</p></section>
    <section><h2>What is active now</h2><div className="info-card-grid info-card-grid--three"><div className="info-card"><Server aria-hidden="true" /><h3>Vercel application</h3><p>Next.js pages and bounded server functions run in the existing Pro team.</p></div><div className="info-card"><Database aria-hidden="true" /><h3>No product database</h3><p>Anonymous checks are not persisted. Neon is planned only when domain claims and managed deployments begin.</p></div><div className="info-card"><HardDrive aria-hidden="true" /><h3>No managed asset store</h3><p>Uploaded source artwork stays local. Vercel Blob is planned for managed SVG and PEM hosting in beta.</p></div></div></section>
    <section><h2>Managed Beta planning envelope</h2><div className="cost-table" role="table" aria-label="Expected incremental cost estimates"><div role="row"><strong role="columnheader">Managed domains</strong><strong role="columnheader">Planning estimate per month</strong></div><div role="row"><span role="cell">1–100</span><span role="cell">Approximately US$0</span></div><div role="row"><span role="cell">1,000</span><span role="cell">Approximately US$0–5</span></div><div role="row"><span role="cell">10,000</span><span role="cell">Approximately US$0–20</span></div><div role="row"><span role="cell">100,000</span><span role="cell">Capacity and support review required</span></div></div><p className="info-small">These are architecture estimates from the service plan, not measured production spending. Actual cost will depend on checks, asset transfer, storage, database activity, alerts, and provider pricing at launch.</p></section>
    <section><h2>Primary pricing references</h2><div className="info-link-list"><a href="https://vercel.com/docs/plans/pro-plan" target="_blank" rel="noreferrer">Vercel Pro plan <ArrowUpRight size={14} aria-hidden="true" /></a><a href="https://vercel.com/docs/storage/vercel-blob/usage-and-pricing" target="_blank" rel="noreferrer">Vercel Blob usage and pricing <ArrowUpRight size={14} aria-hidden="true" /></a><a href="https://neon.com/pricing" target="_blank" rel="noreferrer">Neon pricing <ArrowUpRight size={14} aria-hidden="true" /></a></div></section>
  </InfoPage>;
}
